/**
 * RED guard for: "Pack or strip vendored toolcatalog sourcemaps".
 *
 * THE INVARIANT (remediation-agnostic). The vendored bundle under
 * .publish-stage/dist/_vendor/_klodi_openclaw_* must be internally
 * consistent: a shipped .js may NOT carry a "sourceMappingURL" comment
 * referencing a .js.map that the stage does not contain. For every vendored
 * .js, EITHER it carries no sourceMappingURL comment (the STRIP remediation),
 * OR its referenced .js.map sibling is present in the stage (the PACK
 * remediation). Today neither holds: scripts/vendor.mjs copies each .js
 * verbatim (copyVendorSource -> walkAndCopy -> cpSync, vendor.mjs:143-162)
 * while deliberately excluding .js.map (shouldCopyVendorEntry,
 * vendor.mjs:138-141) and stripping nothing — so the tsc-emitted trailing
 * comment survives and points at an absent artefact. Every downstream load of
 * the published lib then emits a non-fatal "ENOENT" .js.map warning.
 *
 * This test encodes the INVARIANT, not the chosen fix, so it goes GREEN under
 * either remediation. Discovery (3 seats) converged on STRIP, but the test
 * does not assume it — it asserts the consumer contract, not the mechanism.
 *
 * Acceptance criteria:
 *   [unit] AC1 — when each vendored .js under
 *     .publish-stage/dist/_vendor/_klodi_openclaw_* is inspected, none
 *     contains a sourceMappingURL comment (chosen contract: strip). Covers
 *     BOTH _natsclient and _toolcatalog namespaces. (Phrased here as the
 *     strip-OR-pack invariant so either remediation passes.)
 *   [unit] AC4 — negative-scope guard: the SOURCE packages' dist
 *     (tool-catalog, nats-client-ts) must STILL carry sourceMappingURL —
 *     proving the fix is scoped to the vendoring projection and did not bleed
 *     into the deps' build (source tsconfig sourceMap:true is untouched).
 *
 * Placement / runnability. The vendored stage only exists after the real
 * build path produces it: vendor.mjs preflight requires the adapter's dist/
 * AND both workspace deps' dist/. So this test DRIVES the real stage producer
 * (node scripts/vendor.mjs) — the same discipline as
 * manifest-activation-reaches-stage.test.ts — rather than inventing a parallel
 * one. When the build prerequisites are absent (a clean checkout with no
 * dist/), vendor.mjs exits non-zero with a "dist missing" message and no stage
 * is produced; this test then SKIPS LOUDLY (console.warn) — never a silent
 * pass, because a missing build must not delete coverage.
 *
 * DO NOT weaken this test, and DO NOT hand-edit .publish-stage/ to make it
 * pass — the staged copy is generated by vendor.mjs; fix vendor.mjs and let it
 * regenerate the stage.
 */

import { describe, it, expect } from "vitest";
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
// src/__tests__ → adapters/openclaw
const ADAPTER_ROOT = join(HERE, "..", "..");
const REPO_ROOT = join(ADAPTER_ROOT, "..", "..");
const VENDOR_SCRIPT = join(ADAPTER_ROOT, "scripts", "vendor.mjs");
const STAGE_DIR = join(ADAPTER_ROOT, ".publish-stage");
const VENDOR_ROOT = join(STAGE_DIR, "dist", "_vendor");

// vendor.mjs copies an already-built dist tree (no compile, no docker), but
// staging on a cold cache can take a moment — match the sibling test's budget.
const VENDOR_TIMEOUT_MS = 60 * 1000;

// tsc emits exactly this trailing line comment when `sourceMap: true`. The
// referenced map name lives in the capture group so we can check for the
// sibling under the PACK remediation arm.
const SOURCE_MAP_RE = /\/\/#\s*sourceMappingURL=(\S+)/;

interface VendorResult {
  produced: boolean;
  /** Set only when prerequisites were missing, for the loud skip message. */
  reason?: string;
}

/**
 * Run the REAL stage producer. vendor.mjs's own `clean()` wipes
 * `.publish-stage/` first, so we never assert against a stale stage. A
 * non-zero exit with a "<dist> missing" preflight message means the build
 * prerequisites are absent — a SKIP condition, not a failure.
 */
function produceStage(): VendorResult {
  const result = spawnSync("node", [VENDOR_SCRIPT], {
    cwd: ADAPTER_ROOT,
    encoding: "utf8",
    timeout: VENDOR_TIMEOUT_MS,
  });
  const out = `${result.stdout ?? ""}${result.stderr ?? ""}`;

  if (result.status === 0 && existsSync(VENDOR_ROOT)) {
    return { produced: true };
  }
  const prereqMissing = /dist missing|Build workspace deps first|Run `pnpm build`/.test(out);
  return {
    produced: false,
    reason: prereqMissing
      ? "build prerequisites absent (no dist/ — run `pnpm build` + " +
        "`pnpm build:deps` first); vendor.mjs cannot stage"
      : `vendor.mjs exited ${result.status} without producing a stage. Output:\n${out}`,
  };
}

/** Every `.js` under the staged `_vendor/` tree, recursively, absolute paths. */
function vendoredJsFiles(): string[] {
  const out: string[] = [];
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const p = join(dir, entry.name);
      if (entry.isDirectory()) walk(p);
      else if (entry.isFile() && p.endsWith(".js")) out.push(p);
    }
  };
  walk(VENDOR_ROOT);
  return out;
}

const stage = produceStage();

const maybeIt = stage.produced ? it : it.skip;
if (!stage.produced) {
  // eslint-disable-next-line no-console
  console.warn(
    `[vendor-no-dangling-sourcemap] SKIPPED: ${stage.reason}. This is NOT a ` +
      "pass — build the adapter + workspace deps (CI's build:vendored path " +
      "does this) so scripts/vendor.mjs can stage .publish-stage/ and the " +
      "vendored bundle's sourcemap consistency is actually verified.",
  );
}

describe("vendored bundle ships no dangling sourcemap reference", () => {
  // AC1 — the primary invariant. Remediation-agnostic: strip OR pack passes.
  maybeIt(
    "every vendored .js either has no sourceMappingURL or a packed .js.map sibling",
    () => {
      const jsFiles = vendoredJsFiles();

      // Guard the guard: if vendoring ever stops emitting vendored .js, the
      // invariant is vacuously true and would hide a broken stage. The
      // ground-truth is 15 files (8 natsclient + 7 toolcatalog); require the
      // tree to be non-empty and span both namespaces.
      expect(
        jsFiles.length,
        "no vendored .js found under .publish-stage/dist/_vendor/ — vendor.mjs " +
          "produced an empty/partial stage; the invariant cannot be vacuously true.",
      ).toBeGreaterThan(0);
      expect(
        jsFiles.some((f) => f.includes("_klodi_openclaw_natsclient")),
        "no _natsclient vendored .js in the stage — both namespaces must be present.",
      ).toBe(true);
      expect(
        jsFiles.some((f) => f.includes("_klodi_openclaw_toolcatalog")),
        "no _toolcatalog vendored .js in the stage — both namespaces must be present.",
      ).toBe(true);

      // For each vendored .js: a sourceMappingURL is only allowed if the map
      // it points at actually shipped in the stage. Collect violators so the
      // failure lists every dangling reference, not just the first.
      const dangling: string[] = [];
      for (const file of jsFiles) {
        const match = readFileSync(file, "utf8").match(SOURCE_MAP_RE);
        if (!match) continue; // no map reference — STRIP remediation satisfied
        const mapPath = join(dirname(file), match[1]);
        if (!existsSync(mapPath)) {
          dangling.push(`${file} → ${match[1]} (absent)`);
        }
      }

      expect(
        dangling,
        "vendored .js carry sourceMappingURL comments pointing at .js.map files " +
          "absent from the stage — every downstream load emits ENOENT *.js.map. " +
          "Fix vendor.mjs to STRIP the comment (or PACK the maps); do not hand-edit " +
          `.publish-stage/. Dangling references:\n  ${dangling.join("\n  ")}`,
      ).toEqual([]);
    },
  );
});

// AC4 — negative-scope guard. The fix lives in the VENDORING projection, not
// in how the deps build. The source packages keep `sourceMap: true` (local dev
// + cross-language codegen source; ADR-0009 alt #4), so their dist must STILL
// emit sourceMappingURL. This pins the scope boundary: a fix that strips the
// source dists (over-reach) flips this to FAIL. Independent of the stage, so it
// runs even when vendor prerequisites are absent.
describe("source packages' dist still carries sourceMappingURL (scope guard)", () => {
  for (const pkg of ["tool-catalog", "nats-client-ts"] as const) {
    it(`${pkg}/dist *.js retain their sourceMappingURL comments`, () => {
      const distDir = join(REPO_ROOT, "packages", pkg, "dist");
      if (!existsSync(distDir)) {
        // eslint-disable-next-line no-console
        console.warn(
          `[vendor-no-dangling-sourcemap] scope guard SKIPPED for ${pkg}: ` +
            `${distDir} absent — run \`pnpm build:deps\` first. NOT a pass.`,
        );
        return;
      }
      // Top-level .js only (codegen/ is dev tooling, excluded from vendoring).
      const jsWithMap = readdirSync(distDir)
        .filter((n) => n.endsWith(".js"))
        .filter((n) => SOURCE_MAP_RE.test(readFileSync(join(distDir, n), "utf8")));

      expect(
        jsWithMap.length,
        `packages/${pkg}/dist no longer emits sourceMappingURL — the fix bled ` +
          "into the deps' build. The strip must be scoped to the vendoring " +
          "projection (vendor.mjs's staged copy), never the source tsconfig.",
      ).toBeGreaterThan(0);
    });
  }
});
