"""Catalog-level constants exposed to Python adapters.

Loaded from ``schemas.json#constants``, which is generated by the TS
codegen at ``klodi-plugin/packages/tool-catalog/src/codegen/json-schema.ts``.

Adding a new entry to ``KLODI_CATALOG_CONSTANTS`` in the TS catalog
lights it up here automatically — no per-language drift, no hand-maintained
shadow list. See ``docs/reviews/2026-04-26-klodi-plugin-multi-lens-review-decisions.md``
(D9, D14) for the rationale.
"""

from __future__ import annotations

import json
from importlib import resources
from typing import Any


def _load_constants() -> dict[str, Any]:
    """Read the bundled ``schemas.json`` and extract its ``constants`` block.

    Older ``schemas.json`` versions (pre-D9/D14) shipped no constants;
    return an empty mapping in that case so adapters that ship with a
    stale catalog wheel still import cleanly. Public callers should
    fall back to env-var defaults when a constant they need is missing.
    """
    with resources.files(__package__).joinpath("schemas.json").open(
        "r", encoding="utf-8"
    ) as fh:
        loaded = json.load(fh)
    if not isinstance(loaded, dict):
        raise RuntimeError(
            "schemas.json malformed: top-level value must be an object,"
            f" got {type(loaded).__name__}"
        )
    constants = loaded.get("constants", {})
    if not isinstance(constants, dict):
        raise RuntimeError(
            "schemas.json malformed: 'constants' must be an object,"
            f" got {type(constants).__name__}"
        )
    return constants


_CONSTANTS = _load_constants()


def _require_str(name: str) -> str:
    value = _CONSTANTS.get(name)
    if not isinstance(value, str) or not value:
        raise RuntimeError(
            f"klodi catalog: missing required string constant '{name}'."
            " Regenerate codegen via `pnpm --filter @klodi/tool-catalog codegen`."
        )
    return value


def _require_int(name: str) -> int:
    value = _CONSTANTS.get(name)
    if not isinstance(value, int) or isinstance(value, bool):
        raise RuntimeError(
            f"klodi catalog: missing required integer constant '{name}'."
            " Regenerate codegen via `pnpm --filter @klodi/tool-catalog codegen`."
        )
    return value


#: Canonical API base for OAuth registration polling.
KLODI_DEFAULT_API_URL: str = _require_str("KLODI_DEFAULT_API_URL")

#: Canonical NATS-WS URL for the persistent klodi connection.
KLODI_DEFAULT_NATS_URL: str = _require_str("KLODI_DEFAULT_NATS_URL")

def _optional_str(name: str) -> str:
    """Read a catalog string constant that may legitimately be empty.

    Unlike :func:`_require_str`, an empty / missing value is not an
    error — it is a valid pre-cutover state (see ``KLODI_NATS_CA_PEM``).
    """
    value = _CONSTANTS.get(name, "")
    return value if isinstance(value, str) else ""


#: Bundled private-CA PEM trusted for the ``tls://`` L4-proxy transport.
#: Intentionally EMPTY until the epic (`nats-ws-ingress-flap-2026-06`)
#: mints the real CA — an empty value means "fall through to the
#: ``KLODI_NATS_CA_FILE`` override or the system trust store" (see
#: ``klodi_nats_client.tls``). Non-strict: unlike the required string
#: constants above, an empty PEM is a valid pre-cutover state.
KLODI_NATS_CA_PEM: str = _optional_str("KLODI_NATS_CA_PEM")

#: Max ``klodi_channel_message`` body length, in Unicode code-points.
MAX_CHANNEL_MESSAGE_CHARS: int = _require_int("MAX_CHANNEL_MESSAGE_CHARS")

#: Initial poll interval for ``klodi_register_poll`` (seconds).
REGISTER_POLL_INTERVAL_SECONDS: int = _require_int("REGISTER_POLL_INTERVAL_SECONDS")

#: Maximum poll-loop wall-clock duration before surfacing ``expired`` (seconds).
REGISTER_POLL_CEILING_SECONDS: int = _require_int("REGISTER_POLL_CEILING_SECONDS")


__all__ = [
    "KLODI_DEFAULT_API_URL",
    "KLODI_DEFAULT_NATS_URL",
    "KLODI_NATS_CA_PEM",
    "MAX_CHANNEL_MESSAGE_CHARS",
    "REGISTER_POLL_CEILING_SECONDS",
    "REGISTER_POLL_INTERVAL_SECONDS",
]
