/**
 * Canonical klodi_* tool catalog — single source of truth.
 *
 * Each entry:
 *   - subject : NATS subject the marketplace handler listens on
 *   - params  : TypeBox schema for the tool's input parameters
 *   - result  : TypeBox schema for the response shape
 *
 * The TS adapters import this module directly. Python adapters consume
 * `dist/schemas.json` (generated by `pnpm codegen`). Rust adapters consume
 * `dist/rust-types.rs` (also generated by `pnpm codegen`).
 *
 * Local-only tools (klodi_register, klodi_setup_status, klodi_setup_repair,
 * klodi_setup_reseed_policies, klodi_register_poll, klodi_health, klodi_watch,
 * klodi_unwatch, klodi_channel_message) are NOT in this catalog because
 * they don't map 1:1 to a NATS subject — they have local side effects
 * (disk writes, browser polling, JetStream publish, multi-call composition).
 * Adapters register them natively with their host's tool API.
 *
 * `klodi_search` and `klodi_searches_list` ARE in this catalog because they
 * are pure pass-throughs to a single NATS subject.
 */

import { Type, type Static, type TSchema } from "@sinclair/typebox";
import {
  Cents,
  Currency,
  Category,
  CancelReason,
  Condition,
  Handle,
  Iso8601,
  ChannelStatus,
  ListingStatus,
  OfferAction,
  OfferRole,
  OfferStatus,
  Rating,
  Uuid,
} from "./schemas.js";
import { DeliveryFilter, DeliveryOffer, Fulfillment } from "./delivery.js";

export * from "./schemas.js";
export * from "./events.js";
export * from "./logging.js";
export * from "./local-tools.js";
export * from "./delivery.js";

// ─── Common result fragments ──────────────────────────────────────────

const ListingResult = Type.Object({
  listing_id: Uuid,
  listing_url: Type.String(),
  seller_id: Uuid,
  seller_handle: Handle,
  title: Type.String(),
  description: Type.String(),
  category: Category,
  asking_price: Cents,
  currency: Currency,
  fulfillment: Fulfillment,
  condition: Type.Union([Condition, Type.Null()]),
  photos: Type.Array(Type.String()),
  tags: Type.Array(Type.String()),
  status: ListingStatus,
  created_at: Iso8601,
  updated_at: Iso8601,
  expires_at: Type.Union([Iso8601, Type.Null()]),
});

/**
 * Per-rating snapshot. `avg` is the running mean of ratings received in
 * this role; `count` is the number of ratings received. Null when the
 * user has never been rated in this role.
 */
const RatingSnapshot = Type.Union([
  Type.Object({
    avg: Type.Number({ description: "Running mean rating, 1.0–5.0" }),
    count: Type.Integer({
      description: "Number of ratings received in this role",
      minimum: 0,
    }),
  }),
  Type.Null(),
]);

const ListingSearchSummary = Type.Object({
  listing_id: Uuid,
  listing_url: Type.String(),
  title: Type.String(),
  asking_price: Cents,
  currency: Currency,
  category: Category,
  fulfillment: Fulfillment,
  condition: Type.Union([Condition, Type.Null()]),
  distance_km: Type.Optional(Type.Number()),
  seller_handle: Handle,
  seller_rating: Type.Union([Type.Number(), Type.Null()]),
  seller_trades: Type.Integer({ minimum: 0 }),
  photos: Type.Array(Type.String()),
  created_at: Iso8601,
});

const ChannelResult = Type.Object({
  channel_id: Uuid,
  listing_id: Uuid,
  buyer_handle: Handle,
  seller_handle: Handle,
  status: Type.String(),
  created_at: Iso8601,
  expires_at: Iso8601,
});

/**
 * Full offer reply shape. Mirrors the marketplace `offers.create` and
 * `offers.mine` reply — `buyer_id` and `seller_id` are exposed so agents
 * can correlate offers with channel participants without a second roundtrip.
 */
const OfferResult = Type.Object({
  offer_id: Uuid,
  listing_id: Uuid,
  channel_id: Uuid,
  buyer_id: Uuid,
  seller_id: Uuid,
  buyer_handle: Handle,
  amount: Cents,
  currency: Currency,
  message: Type.Union([Type.String(), Type.Null()]),
  terms: Type.Union([Type.Object({}, { additionalProperties: true }), Type.Null()]),
  status: Type.String(),
  transaction_id: Type.Union([Uuid, Type.Null()]),
  created_at: Iso8601,
  responded_at: Type.Union([Iso8601, Type.Null()]),
});

/**
 * Confirm/cancel reply shape. `final_amount` is the cents amount the
 * buyer agreed to pay; `completed_at` and `cancelled_at` are populated
 * once the transaction reaches the corresponding terminal state.
 */
const TransactionLifecycleResult = Type.Object({
  transaction_id: Uuid,
  status: Type.String(),
  buyer_confirmed: Type.Boolean(),
  seller_confirmed: Type.Boolean(),
  final_amount: Cents,
  completed_at: Type.Union([Iso8601, Type.Null()]),
});

// ─── Catalog ──────────────────────────────────────────────────────────

export interface ToolEntry<P extends TSchema = TSchema, R extends TSchema = TSchema> {
  subject: string;
  params: P;
  result: R;
  description: string;
}

/**
 * Canonical klodi_* tool catalog. Each tool is keyed by its public name
 * (the name agents call) and wraps a single NATS subject.
 */
export const klodiTools = {
  // ─── Identity ───────────────────────────────────────────────────────

  klodi_whoami: {
    subject: "p2p.v1.users.whoami",
    description:
      "Check your identity, ratings, and profile on klodi."
      + " Returns handle, per-role ratings + counts, trade counts,"
      + " location, and profile metadata.",
    params: Type.Object({}),
    result: Type.Object({
      user_id: Uuid,
      handle: Handle,
      buyer_rating: RatingSnapshot,
      seller_rating: RatingSnapshot,
      trades_as_buyer: Type.Integer({ minimum: 0 }),
      trades_as_seller: Type.Integer({ minimum: 0 }),
      location_area: Type.Union([Type.String(), Type.Null()]),
      country_code: Type.Union([Type.String(), Type.Null()]),
      administrative_area: Type.Union([Type.String(), Type.Null()]),
      city: Type.Union([Type.String(), Type.Null()]),
      postal_code: Type.Union([Type.String(), Type.Null()]),
      bio: Type.Union([Type.String(), Type.Null()]),
      avatar_url: Type.Union([Type.String(), Type.Null()]),
      member_since: Iso8601,
    }),
  },

  klodi_ratings: {
    subject: "p2p.v1.ratings.query",
    description:
      "Look up any user's public marketplace ratings and profile."
      + " Returns per-role ratings, trade counts, and public profile"
      + " fields (location, bio, avatar).",
    params: Type.Object({ handle: Handle }),
    result: Type.Object({
      handle: Handle,
      buyer_rating: RatingSnapshot,
      seller_rating: RatingSnapshot,
      trades_as_buyer: Type.Integer({ minimum: 0 }),
      trades_as_seller: Type.Integer({ minimum: 0 }),
      location_area: Type.Union([Type.String(), Type.Null()]),
      bio: Type.Union([Type.String(), Type.Null()]),
      avatar_url: Type.Union([Type.String(), Type.Null()]),
      member_since: Iso8601,
    }),
  },

  // ─── Listings ───────────────────────────────────────────────────────

  klodi_list_create: {
    subject: "p2p.v1.listings.create",
    description:
      "Create a new marketplace listing. Prices in integer cents."
      + " `fulfillment` is a discriminated union — at least one offer,"
      + " at most one entry per method. Condition required when any"
      + " offer is pickup or ship; rejected when only digital. `photos`"
      + " accepts image URLs or absolute local file paths — local paths"
      + " are uploaded automatically (jpeg/png/webp, ≤10 MB, ≤10 entries,"
      + " all-or-nothing).",
    params: Type.Object({
      title: Type.String({ description: "Item title (1-200 chars)" }),
      description: Type.String({ description: "Item description (1-2000 chars)" }),
      category: Category,
      asking_price: Cents,
      fulfillment: Fulfillment,
      condition: Type.Optional(Condition),
      photos: Type.Optional(Type.Array(Type.String(), {
        description:
          "Image URLs or absolute local file paths; locals are uploaded"
          + " by the adapter (image/jpeg, image/png, image/webp, ≤10 MB"
          + " each, ≤10 entries).",
      })),
      tags: Type.Optional(Type.Array(Type.String(), {
        description: "Search tags",
      })),
      currency: Type.Optional(Currency),
      expires_hours: Type.Optional(Type.Integer({
        description:
          "Hours until expiry. Omit (or pass null) for no expiry — the"
          + " default. Set a positive integer to give the listing a TTL.",
      })),
    }),
    result: ListingResult,
  },

  klodi_list_update: {
    subject: "p2p.v1.listings.update",
    description:
      "Update an existing listing. Cannot change `category` (withdraw"
      + " and relist instead). Updating `fulfillment` replaces the"
      + " entire array atomically. `expires_hours` sets a fresh TTL from"
      + " now, or pass null to clear the expiry entirely. `photos`"
      + " accepts image URLs or absolute local file paths — local paths"
      + " are uploaded automatically (jpeg/png/webp, ≤10 MB, ≤10 entries,"
      + " full-array replacement is all-or-nothing).",
    params: Type.Object({
      listing_id: Uuid,
      title: Type.Optional(Type.String()),
      description: Type.Optional(Type.String()),
      asking_price: Type.Optional(Cents),
      condition: Type.Optional(Condition),
      fulfillment: Type.Optional(Fulfillment),
      photos: Type.Optional(Type.Array(Type.String(), {
        description:
          "Image URLs or absolute local file paths; locals are uploaded"
          + " by the adapter (image/jpeg, image/png, image/webp, ≤10 MB"
          + " each, ≤10 entries).",
      })),
      tags: Type.Optional(Type.Array(Type.String())),
      currency: Type.Optional(Currency),
      status: Type.Optional(ListingStatus),
      expires_hours: Type.Optional(
        Type.Union([Type.Integer({ minimum: 1 }), Type.Null()]),
      ),
    }),
    result: ListingResult,
  },

  klodi_list_get: {
    subject: "p2p.v1.listings.get",
    description:
      "Get full listing details including seller profile and comments.",
    params: Type.Object({ listing_id: Uuid }),
    result: ListingResult,
  },

  klodi_list_mine: {
    subject: "p2p.v1.listings.mine",
    description: "Get your own listings. Filter by status.",
    params: Type.Object({
      status: Type.Optional(ListingStatus),
    }),
    result: Type.Object({
      listings: Type.Array(ListingResult),
    }),
  },

  klodi_list_withdraw: {
    subject: "p2p.v1.listings.update",
    description:
      "Withdraw a listing (sets status=withdrawn). Cancels active"
      + " transactions, rejects proposed offers, closes channels.",
    params: Type.Object({ listing_id: Uuid }),
    result: ListingResult,
  },

  klodi_list_relist: {
    subject: "p2p.v1.listings.update",
    description:
      "Relist a withdrawn listing (sets status=active). Optionally"
      + " set a new asking price (integer cents).",
    params: Type.Object({
      listing_id: Uuid,
      asking_price: Type.Optional(Cents),
    }),
    result: ListingResult,
  },

  klodi_list_comments: {
    subject: "p2p.v1.comments.list",
    description:
      "Fetch the comment history on a listing in chronological order."
      + " Use before replying to avoid duplicate answers.",
    params: Type.Object({
      listing_id: Uuid,
      limit: Type.Optional(Type.Integer({
        description: "Max comments (default 50, max 200)",
      })),
      before: Type.Optional(Type.String({
        description: "Cursor — comment_id; return older",
      })),
      after: Type.Optional(Type.String({
        description: "Cursor — comment_id; return newer",
      })),
    }),
    result: Type.Object({
      comments: Type.Array(Type.Object({
        comment_id: Uuid,
        listing_id: Uuid,
        handle: Handle,
        body: Type.String(),
        mentions: Type.Array(Type.String()),
        created_at: Iso8601,
      })),
    }),
  },

  // ─── Discovery / search ────────────────────────────────────────────

  klodi_search: {
    subject: "p2p.v1.listings.search",
    description:
      "One-shot search of active listings. `delivery` is a"
      + " discriminated union — pickup, ship, digital, or any."
      + " Each variant exposes only the fields that are meaningful"
      + " for it (pickup → radiusKm; ship → to; digital/any → none).",
    params: Type.Object({
      query: Type.Optional(Type.String()),
      category: Type.Optional(Category),
      min_price: Type.Optional(Cents),
      max_price: Type.Optional(Cents),
      delivery: Type.Optional(DeliveryFilter),
      condition: Type.Optional(Condition),
      limit: Type.Optional(Type.Integer({ description: "Max results (default 20)" })),
      cursor: Type.Optional(Type.String()),
    }),
    result: Type.Object({
      results: Type.Array(ListingSearchSummary),
      total: Type.Integer({
        description: "Number of results returned in this page",
        minimum: 0,
      }),
    }),
  },

  klodi_searches_create: {
    subject: "p2p.v1.searches.create",
    description:
      "Register a persistent (standing) search. The marketplace"
      + " evaluates new listings against this search and emits a"
      + " `search.match` notification on every match. `delivery`"
      + " defaults to { method: 'any' } when omitted.",
    params: Type.Object({
      slug: Type.String({
        description: "Stable client-chosen slug. Last-write-wins per (user, slug).",
      }),
      query: Type.Optional(Type.String()),
      category: Type.Optional(Category),
      min_price: Type.Optional(Cents),
      max_price: Type.Optional(Cents),
      delivery: Type.Optional(DeliveryFilter),
    }),
    result: Type.Object({
      search_id: Uuid,
      slug: Type.String(),
      status: Type.Literal("active"),
      criteria: Type.Object(
        {
          query: Type.Union([Type.String(), Type.Null()]),
          category: Type.Union([Category, Type.Null()]),
          delivery: DeliveryFilter,
          min_price: Type.Union([Cents, Type.Null()]),
          max_price: Type.Union([Cents, Type.Null()]),
        },
        { additionalProperties: false },
      ),
    }),
  },

  klodi_searches_delete: {
    subject: "p2p.v1.searches.delete",
    description: "Delete a standing search by slug.",
    params: Type.Object({ slug: Type.String() }),
    result: Type.Object({
      slug: Type.String(),
      status: Type.Literal("deleted"),
      deleted: Type.Integer({
        description: "Number of standing-search rows removed (0 if none matched)",
        minimum: 0,
      }),
    }),
  },

  klodi_searches_list: {
    subject: "p2p.v1.searches.list",
    description:
      "List your active standing searches. Diagnostic — local buy/<slug>.md"
      + " files are the source of truth for evaluation criteria.",
    params: Type.Object({}),
    result: Type.Object({
      searches: Type.Array(Type.Object({
        search_id: Uuid,
        slug: Type.String(),
        criteria: Type.Object(
          {
            query: Type.Union([Type.String(), Type.Null()]),
            category: Type.Union([Category, Type.Null()]),
            delivery: DeliveryFilter,
            min_price: Type.Union([Cents, Type.Null()]),
            max_price: Type.Union([Cents, Type.Null()]),
          },
          { additionalProperties: false },
        ),
        created_at: Iso8601,
        updated_at: Iso8601,
      })),
    }),
  },

  // ─── Channels (open / list / history / close) ─────────────────────

  klodi_channel_create: {
    subject: "p2p.v1.channels.create",
    description:
      "Open a private negotiation channel on a listing."
      + " Idempotent — returns the existing channel if one is open."
      + " Cannot open on your own listing.",
    params: Type.Object({ listing_id: Uuid }),
    result: ChannelResult,
  },

  klodi_channel_mine: {
    subject: "p2p.v1.channels.mine",
    description:
      "List your active negotiation channels. Filter by status."
      + " Returns counterparty handle and listing title for each.",
    params: Type.Object({
      status: Type.Optional(ChannelStatus),
    }),
    result: Type.Object({
      channels: Type.Array(Type.Object({
        channel_id: Uuid,
        listing_id: Uuid,
        listing_title: Type.String(),
        other_handle: Handle,
        status: Type.String(),
        last_message_at: Iso8601,
        expires_at: Iso8601,
      })),
    }),
  },

  klodi_channel_history: {
    subject: "p2p.v1.channels.history",
    description:
      "Read message history for a channel in chronological order."
      + " Use only when you need history beyond the latest wake — wakes"
      + " carry full message content.",
    params: Type.Object({
      channel_id: Uuid,
      limit: Type.Optional(Type.Integer({
        description: "Max messages (default 50)",
      })),
      before: Type.Optional(Type.String({
        description: "Cursor — message_id; return older",
      })),
      after: Type.Optional(Type.String({
        description: "Cursor — message_id; return newer",
      })),
    }),
    result: Type.Object({
      messages: Type.Array(Type.Object({
        message_id: Uuid,
        sender_handle: Handle,
        content: Type.String(),
        created_at: Iso8601,
      })),
    }),
  },

  klodi_channel_close: {
    subject: "p2p.v1.channels.close",
    description:
      "Close a negotiation channel. Removes server-side filter for both"
      + " participants — no further messages will be received.",
    params: Type.Object({
      channel_id: Uuid,
      reason: Type.Optional(Type.String()),
    }),
    result: Type.Object({
      channel_id: Uuid,
      status: Type.String(),
      closed_at: Iso8601,
    }),
  },

  // ─── Comments (post one) ───────────────────────────────────────────

  klodi_comment: {
    subject: "p2p.v1.comments.create",
    description:
      "Post a public comment on an active listing. Use @handle to"
      + " mention. Max 1000 characters.",
    params: Type.Object({
      listing_id: Uuid,
      body: Type.String({
        description: "Comment text (1-1000 chars)",
        minLength: 1,
        maxLength: 1000,
      }),
    }),
    result: Type.Object({
      comment_id: Uuid,
      listing_id: Uuid,
      handle: Handle,
      body: Type.String(),
      mentions: Type.Array(Type.String()),
      created_at: Iso8601,
    }),
  },

  // ─── Offers ────────────────────────────────────────────────────────

  klodi_offer_create: {
    subject: "p2p.v1.offers.create",
    description:
      "Submit a formal offer on a listing through an open channel."
      + " Amount in integer cents. One proposed offer per channel."
      + " Optional `terms` captures structured deal contract (max 4KB).",
    params: Type.Object({
      listing_id: Uuid,
      channel_id: Uuid,
      amount: Cents,
      currency: Type.Optional(Currency),
      message: Type.Optional(Type.String({
        description: "Optional message (max 500 chars)",
      })),
      terms: Type.Optional(Type.Object({}, {
        additionalProperties: true,
        description:
          "Structured deal terms. Opaque to server, max 4KB.",
      })),
    }),
    result: OfferResult,
  },

  klodi_offer_respond: {
    subject: "p2p.v1.offers.respond",
    description:
      "Accept or reject an offer. Only the seller can respond."
      + " Accepting creates a transaction and moves the listing to"
      + " on_hold; rejecting leaves the listing active.",
    params: Type.Object({
      offer_id: Uuid,
      action: OfferAction,
    }),
    result: Type.Object({
      offer_id: Uuid,
      status: Type.String(),
      listing_id: Type.Optional(Uuid),
      listing_status: Type.Optional(ListingStatus),
      transaction_id: Type.Optional(Uuid),
      responded_at: Iso8601,
    }),
  },

  klodi_offer_mine: {
    subject: "p2p.v1.offers.mine",
    description:
      "List offers involving you. Filter by status, role, listing,"
      + " or channel.",
    params: Type.Object({
      status: Type.Optional(OfferStatus),
      role: Type.Optional(OfferRole),
      listing_id: Type.Optional(Uuid),
      channel_id: Type.Optional(Uuid),
    }),
    result: Type.Object({
      offers: Type.Array(OfferResult),
    }),
  },

  // ─── Transactions ──────────────────────────────────────────────────

  klodi_tx_confirm: {
    subject: "p2p.v1.transactions.confirm",
    description:
      "Confirm completion of a transaction. Both parties must confirm"
      + " before the listing moves to sold. completed_at is null until"
      + " both parties have confirmed.",
    params: Type.Object({ transaction_id: Uuid }),
    result: TransactionLifecycleResult,
  },

  klodi_tx_cancel: {
    subject: "p2p.v1.transactions.cancel",
    description:
      "Cancel a transaction. Listing returns to active. Penalized"
      + " reasons (no_show, item_not_received, payment_not_received)"
      + " auto-apply a 1-star rating to the counterparty.",
    params: Type.Object({
      transaction_id: Uuid,
      reason: CancelReason,
      detail: Type.Optional(Type.String()),
    }),
    result: Type.Object({
      transaction_id: Uuid,
      listing_id: Uuid,
      status: Type.Literal("cancelled"),
      cancelled_by: Handle,
      cancellation_reason: CancelReason,
      listing_status: ListingStatus,
      cancelled_at: Iso8601,
    }),
  },

  klodi_tx_rate: {
    subject: "p2p.v1.transactions.rate",
    description:
      "Rate the counterparty (1-5 stars) after confirming the exchange."
      + " other_party_rated indicates whether the other side has also"
      + " submitted a rating yet.",
    params: Type.Object({
      transaction_id: Uuid,
      rating: Rating,
      comment: Type.Optional(Type.String()),
    }),
    result: Type.Object({
      transaction_id: Uuid,
      listing_id: Uuid,
      rating: Rating,
      comment: Type.Union([Type.String(), Type.Null()]),
      rated_handle: Handle,
      rated_role: Type.Union([Type.Literal("buyer"), Type.Literal("seller")]),
      other_party_rated: Type.Boolean(),
    }),
  },

  klodi_tx_status: {
    subject: "p2p.v1.transactions.status",
    description:
      "Check transaction status: both confirmation flags, ratings, comments,"
      + " cancellation context, and the next_action hint for the caller.",
    params: Type.Object({ transaction_id: Uuid }),
    result: Type.Object({
      transaction_id: Uuid,
      offer_id: Uuid,
      listing_id: Uuid,
      listing_title: Type.String(),
      buyer_id: Uuid,
      seller_id: Uuid,
      buyer_handle: Handle,
      seller_handle: Handle,
      your_role: Type.Union([Type.Literal("buyer"), Type.Literal("seller")]),
      other_handle: Handle,
      final_amount: Cents,
      currency: Currency,
      terms: Type.Union([Type.Object({}, { additionalProperties: true }), Type.Null()]),
      status: Type.String(),
      buyer_confirmed: Type.Boolean(),
      seller_confirmed: Type.Boolean(),
      rating_by_buyer: Type.Union([Rating, Type.Null()]),
      rating_by_seller: Type.Union([Rating, Type.Null()]),
      comment_by_buyer: Type.Union([Type.String(), Type.Null()]),
      comment_by_seller: Type.Union([Type.String(), Type.Null()]),
      cancellation_reason: Type.Union([CancelReason, Type.Null()]),
      cancelled_by: Type.Union([Handle, Type.Null()]),
      next_action: Type.Union([Type.String(), Type.Null()]),
      created_at: Iso8601,
      completed_at: Type.Union([Iso8601, Type.Null()]),
      cancelled_at: Type.Union([Iso8601, Type.Null()]),
    }),
  },

} as const;

export type ToolName = keyof typeof klodiTools;

/** Compile-time list of every tool name in the catalog. */
export const TOOL_NAMES: readonly ToolName[] = Object.keys(klodiTools) as ToolName[];

/** Static type helpers for adapters that need to derive types from a tool. */
export type ToolParams<N extends ToolName> = Static<(typeof klodiTools)[N]["params"]>;
export type ToolResult<N extends ToolName> = Static<(typeof klodiTools)[N]["result"]>;

/** Lookup the subject for a tool by name. */
export function subjectOf<N extends ToolName>(name: N): string {
  return klodiTools[name].subject;
}

// ─── Cross-language constants (codegen into Py + Rust) ────────────────
//
// These are the single source of truth. The codegen pipeline emits them
// into `dist/schemas.json` (consumed by Python adapters via
// `klodi_nats_client.constants`) and into `dist/rust-types.rs` (consumed
// by Rust adapters via `klodi_nats_client::catalog`).
//
// Per `klodi-plugin/SECURITY.md` and `docs/reviews/2026-04-26-klodi-plugin-multi-lens-review-decisions.md`:
//   - D9 — canonical API + NATS URLs
//   - D14 — channel-message length cap (Unicode code-points)
//
// To override the API URL at adapter level: set `KLODI_API_URL` env var.
// To override the NATS URL: set `KLODI_NATS_URL` env var (or persist
// after registration in `${klodi_home}/config.json`).

/** Canonical API base for OAuth registration polling. */
export const KLODI_DEFAULT_API_URL = "https://klodi.4gpts.com";

/** Canonical NATS-WS URL for the persistent klodi connection. */
export const KLODI_DEFAULT_NATS_URL = "wss://klodi-net.4gpts.com";

/**
 * Max length for a `klodi_channel_message` body, in Unicode code-points.
 * Aligned with the `channel_messages.body` Postgres `varchar` cap and
 * the cross-language counting convention (Py `len()`, Rust `.chars().count()`,
 * TS `[...content].length`).
 */
export const MAX_CHANNEL_MESSAGE_CHARS = 2000;

/**
 * Initial poll interval for `klodi_register_poll`. Per **R § P2-10**:
 * the prior 5s value was duplicated in three adapters; promote the
 * cadence to the catalog so all hosts agree.
 */
export const REGISTER_POLL_INTERVAL_SECONDS = 5;

/**
 * Maximum wall-clock duration the registration poll loop runs before
 * surfacing `expired`. 600s = 10min — long enough to walk a user
 * through a browser OAuth flow with an interruption.
 */
export const REGISTER_POLL_CEILING_SECONDS = 600;

/**
 * Map of catalog-level constants the codegen pipeline emits into
 * Python (`schemas.json#constants`) and Rust (`rust-types.rs` consts).
 * Adding a new constant here lights it up in both downstream languages.
 */
export const KLODI_CATALOG_CONSTANTS = {
  KLODI_DEFAULT_API_URL,
  KLODI_DEFAULT_NATS_URL,
  MAX_CHANNEL_MESSAGE_CHARS,
  REGISTER_POLL_INTERVAL_SECONDS,
  REGISTER_POLL_CEILING_SECONDS,
} as const;

export type KlodiCatalogConstantName = keyof typeof KLODI_CATALOG_CONSTANTS;
